GearMVC/Controllers/Admin/ManufactuerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Domain.Entity;
using Domain.IRepository;
using Microsoft.AspNetCore.Mvc;
using Application.DTO;
using AutoMapper.Configuration.Conventions;
using Application.Mapping;
using Application.ViewModels;
using GearMVC.Services;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Authorization;

namespace GearMVC.Controllers
{
    [Route("admin/[controller]")]
    [Authorize(Roles = "Nhân viên, Admin, Quản lý")]
    public class ManufactuerController : Controller
    {
        private readonly INhaCungCapRepository _nccRepo;
        private readonly IMapper _mapper;
        private readonly int ItemPerPage = 10;
        public ManufactuerController(INhaCungCapRepository nccRepo, IMapper mapper)
        {
            _nccRepo = nccRepo;
            _mapper = mapper;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index(string searchString = "", int page = 1)
        {
            if (searchString == null) searchString = "";

            IEnumerable<NhaCungCap> list = await _nccRepo.Filter(searchString);
            double count = list.Count();
            double i = (double)(count / ItemPerPage);
            var pageCount = (int)Math.Ceiling(i);


            list = list.Skip((page - 1) * ItemPerPage).Take(ItemPerPage).ToList();
            List<NhaCungCapDTO> nccs = _mapper.Map<List<NhaCungCapDTO>>(list);


            IndexViewModel<NhaCungCapDTO> returnList = PaginationServices<NhaCungCapDTO>.Pagination(nccs, page, ItemPerPage, pageCount, searchString);

            return View("~/Views/Admin/Manufactuer/Index.cshtml", returnList);
        }
        [HttpGet("Add")]
        [Authorize(Roles = "Admin, Quản lý")]
        public IActionResult Add()
        {
            NhaCungCapDTO dto = new NhaCungCapDTO();
            ViewBag.Title = "Thêm Nhà Sản Xuất";
            return View("~/Views/Admin/Manufactuer/Add.cshtml", dto);
        }

        [HttpPost("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost(NhaCungCapDTO dto)
        {
            var message = "";
            if (!ModelState.IsValid)
            {
                return View("~/Views/Admin/Manufactuer/Add.cshtml", dto);
            }


            message = "Tạo thành công";
            ViewBag.Message = message;
            ViewBag.Title = "Thêm Chủng Loại";
            NhaCungCap ncc = _mapper.Map<NhaCungCap>(dto);
            await _nccRepo.Add(ncc);
            return View("~/Views/Admin/Manufactuer/Add.cshtml", dto);

        }
        [HttpGet("{id?}/Edit")]
        [Authorize(Roles = "Admin, Quản lý")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Title = "Sửa Nhà Sản Xuất";
            NhaCungCap ncc = await _nccRepo.getById(id);
            if (ncc == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            NhaCungCapDTO dto = _mapper.Map<NhaCungCapDTO>(ncc);
            return View("~/Views/Admin/Manufactuer/Edit.cshtml", dto);
        }

        [HttpPost("{id?}/Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int id, NhaCungCapDTO dto)
        {
            ViewBag.Title = "Sửa Chủng Loại";
            var message = "";
            NhaCungCap ncc = await _nccRepo.getById(id);

            if (!ModelState.IsValid)
            {
                return View("~/Views/Admin/Manufactuer/Edit.cshtml", dto);
            }

            //Update Du Lieu
            ncc = dto.NhaCungCapEditMap(ncc);
            await _nccRepo.Update(ncc);
            message = "Sửa thành công";
            ViewBag.Message = message;
            return View("~/Views/Admin/Manufactuer/Edit.cshtml", dto);
        }

        [HttpPost("{id?}/Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Quản lý")]
        public async Task<IActionResult> Delete(int id)
        {
            var ncc = await _nccRepo.getById(id);
            if (ncc == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            await _nccRepo.Delete(ncc);
            return Redirect("/admin/manufactuer");
        }
    }
}

GearMVC/Views/Admin/Manufactuer/Add.cshtml
@model Application.DTO.NhaCungCapDTO

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".nhacungcap").addClass("admin-active");
        });
    </script>
}

@section Content{
    <div>
        <div class="admin-content-title"><b>Thêm nhà sản xuất</b></div>
        <div class="admin-content">
            <div class="admin-form">
                @if (ViewBag.Message != null && ViewBag.Message != "")
                {
                    <div class="alert alert-success admin-error">@ViewBag.Message</div>
                }
                @Html.ValidationSummary(true)
            <form id="catalogAdd" method="post" name="catalogAdd" action="@Url.Action("AddPost", "Manufactuer")">
                <div class="admin-error row">
                    <div class="col-sm-3"></div>
                    <div>
                        @Html.ValidationMessageFor(m => m.MaNCC, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label for="MaNCC" class="col-sm-3 col-form-label">Mã Loại</label>
                    <div class="col-sm-8"><input type="text" class="form-control" id="MaNCC" name="MaNCC" value="@Model.MaNCC"></div>
                </div>
                <div class="admin-error row">
                    <div class="col-sm-3"></div>
                    <div>
                        @Html.ValidationMessageFor(m => m.TenNCC, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label for="TenNCC" class="col-sm-3 col-form-label">Tên</label>
                    <div class="col-sm-8"><input type="text" class="form-control" id="TenNCC" name="TenNCC" value="@Model.TenNCC"></div>
                </div>
                <div class="form-group row">
                    <label for="MoTa" class="col-sm-3 col-form-label">Mô tả</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" cols="4" rows="5" name="MoTa">@Model.MoTa</textarea>
                    </div>
                </div>
                @Html.AntiForgeryToken()
                <div class="form-group row">
                    <div class="admin-form-edit-button">
                        <button class="btn btn-warning admin-form-edit-button" type="submit"
                                form="catalogAdd" value="Submit">
                            Tạo
                        </button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
}

GearMVC/Views/Admin/Manufactuer/Edit.cshtml
@model Application.DTO.NhaCungCapDTO

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".nhacungcap").addClass("admin-active");
        });
    </script>
}

@section Content{
    <div>
        <div class="admin-content-title"><b>Sửa nhà sản xuất</b></div>
        <div class="admin-content">
            <div class="admin-form">
                @if (ViewBag.Message != null && ViewBag.Message != "")
                {
                    <div class="alert alert-success admin-error">@ViewBag.Message</div>
                }
                @Html.ValidationSummary(true)

            <form id="catalogAdd" method="post" name="catalogAdd" action="@Url.Action("EditPost", "Manufactuer", new { id = Model.Id })">
                <div class="admin-error row">
                    <div class="col-sm-3"></div>
                    <div>
                        @Html.ValidationMessageFor(m => m.MaNCC, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Name" class="col-sm-3 col-form-label">Mã Loại</label>
                    <div class="col-sm-8"><input data-val="true" type="text" class="form-control" id="MaNCC" name="MaNCC" value="@Model.MaNCC"></div>
                </div>
                <div class="admin-error row">
                    <div class="col-sm-3"></div>
                    <div>
                        @Html.ValidationMessageFor(m => m.TenNCC, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Name" class="col-sm-3 col-form-label">Tên</label>
                    <div class="col-sm-8"><input data-val="true" type="text" class="form-control" id="TenNCC" name="TenNCC" value="@Model.TenNCC"></div>
                </div>
                <div class="form-group row">
                    <label for="MoTa" class="col-sm-3 col-form-label">Mô tả</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" cols="4" rows="5" name="MoTa">@Model.MoTa</textarea>
                    </div>
                </div>
                @Html.AntiForgeryToken()
                <div class="form-group row">
                    <div class="admin-form-edit-button">
                        <button class="btn btn-warning admin-form-edit-button" type="submit"
                                form="catalogAdd" value="Submit">
                            Sửa
                        </button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
}

GearMVC/Views/Admin/Manufactuer/Index.cshtml
@model IndexViewModel<Application.DTO.NhaCungCapDTO>

@{
    ViewData["Title"] = "Quản lý nhà sản xuất";
    var count = 0;
    var searchString = (Model.searchString == null) ? "" : Model.searchString;
}

@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            $(".nhacungcap").addClass("admin-active");

            $(".delete").click(function (e) {
                e.preventDefault();
                if (confirm("Bạn chắc chắn muốn xóa?")) {
                    $(this).parents('form').submit();
                }
            });
        });
    </script>
}

@section Content {
    <div>
        <div class="admin-content-title"><b>QUẢN LÝ NHÀ SẢN XUẤT</b></div>
        <div class="admin-content">
            <div class="admin-filter">
                <div class="row">
                    <div class="col-2"><span>TÌM KIẾM</span></div>
                    <div class="col-10">
                        <form id="searchForm" name="searchForm" method="get" action="@Url.Action("Index", "Manufactuer")">
                            <input type="text" class="admin-input" name="searchString"
                                   value="@searchString">
                            <button class="admin-button-submit" type="submit"
                                form="searchForm" value="Submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                    </div><a href="@Url.Action("Add","Manufactuer")">
                        <div class="admin-plus"><span><i class="fas fa-plus-circle"></i></span></div>
                    </a>
                </div>
            </div>
            <div class="admin-content-title-1"><span class="admin-border-title-1">THÔNG TIN NHÀ SẢN XUẤT</span></div>
            <div class="margin-top-20">
                <table class="table table-striped table-condensed" width="100%">
                    <thead>
                        <tr class="d-flex">
                            <th class="col-1">#</th>
                            <th class="col-2">Mã</th>
                            <th class="col-5">Tên</th>
                            <th class="col-4">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Entities)
                        {
                            count++;
                        <tr class="d-flex">
                            <th class="col-1">@count</th>
                            <td class="col-2">@item.MaNCC</td>
                            <td class="col-5">@item.TenNCC</td>
                            <td class="col-4">
                                <a href="@Url.Action("Edit", "Manufactuer", new { id = item.Id})">
                                    <button class="admin-button edit">
                                        <i class="fas fa-edit"
                                           data-catalog="1"></i>
                                    </button>
                                </a>
                                <form method="post" id="delete" action="/admin/manufactuer/@item.Id/delete" style="display:inline;">
                                    @Html.AntiForgeryToken()
                                    <button class="admin-button delete" data-ncc="@item.Id">
                                        <i class="fas fa-trash-alt" data-ncc="@item.Id"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            @{
                await Html.RenderPartialAsync(
                  "Pagination",
                   new ViewDataDictionary(this.Vi‌​ewData) {{"nameFunction", "Index"},{ "nameAction", "Manufactuer" }});
            }
        </div>
    </div>
}