GearMVC/Controllers/Admin/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.DTO;
using Application.ViewModels;
using AutoMapper;
using Domain.IRepository;
using GearMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GearMVC.Controllers.Admin
{
    [Route("admin/order")]
    [Authorize(Roles = "Nhân viên, Admin, Quản lý")]
    public class DonHangController : Controller
    {
        public readonly IHoaDonRepository _hoadonRepo;
        private readonly IMapper _mapper;
        private readonly int ItemPerPage = 8;

        public DonHangController(IHoaDonRepository hoadonRepo, IMapper mapper)
        {
            _hoadonRepo = hoadonRepo;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string searchString = "", string tinhTrang = "", string orderBy = "", DateTime fromDate = default, DateTime toDate = default, int page = 1)
        {
            if (searchString == null) searchString = "";
            if (orderBy == null) orderBy = "";

            var list = await _hoadonRepo.Filter(searchString, orderBy, tinhTrang, fromDate, toDate);
            double count = list.Count();
            double i = (double)(count / ItemPerPage);
            var pageCount = (int)Math.Ceiling(i);

            list = list.Skip((page - 1) * ItemPerPage).Take(ItemPerPage).ToList();
            List<HoaDonDTO> hoadonsDTO = _mapper.Map<List<HoaDonDTO>>(list);

            IndexViewModel<HoaDonDTO> returnList = PaginationServices<HoaDonDTO>.PaginationHoaDon(hoadonsDTO, page, ItemPerPage, pageCount, searchString, tinhTrang, orderBy, fromDate, toDate);

            return View("~/Views/Admin/DonHang/Index.cshtml", returnList);
        }

        [HttpGet("{id?}/edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var donHang = await _hoadonRepo.getById(id);

            if (donHang == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            var dto = _mapper.Map<HoaDonDTO>(donHang);

            return View("~/Views/Admin/DonHang/Edit.cshtml", dto);

        }

        [HttpPost("{id?}/edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int id, string tinhTrang)
        {
            var donHang = await _hoadonRepo.getById(id);

            donHang.TinhTrang = tinhTrang;

            await _hoadonRepo.Update(donHang);

            return Redirect("/admin/order");
        }


    }
}

GearMVC/Controllers/Admin/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Application.DTO;
using AutoMapper;
using Domain.Entity;
using Domain.IRepository;
using Application.ViewModels;
using GearMVC.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace GearMVC.Controllers.Admin
{
    [Route("admin/[controller]")]
    [Authorize(Roles = "Nhân viên, Admin, Quản lý")]
    public class ProductController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILinhKienRepository _linhKienRepository;
        private readonly ILoaiLinhKienRepository _llkRepository;
        private readonly INhaCungCapRepository _nccRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly int itemPerPage = 10;

        public ProductController(IMapper mapper, ILinhKienRepository linhKienRepository, ILoaiLinhKienRepository llkRepository, INhaCungCapRepository nccRepository, IWebHostEnvironment webHostEnvironment)
        {
            _mapper = mapper;
            _linhKienRepository = linhKienRepository;
            _llkRepository = llkRepository;
            _nccRepository = nccRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        /*
            searchString: Những kí tự muốn search
            searchCategory: id Loại Linh Kiện của các sản phẩm muốn lấy ra
            searchManu: id Nhà Cung Cấp của các sản phẩm muốn lấy ra
            page: trang hiện tại
         */
        public async Task<IActionResult> Index(string searchString = "", int searchCategory = 0, int searchManu = 0, int page = 1)
        {
            if (searchString == null) searchString = "";

            //Get All LinhKien with search
            var linhkiens = await _linhKienRepository.Filter(searchString, searchCategory, searchManu);
            double count = linhkiens.Count();
            int pageCount = (int)Math.Ceiling(count / itemPerPage);
            var LKPagination = linhkiens.Skip((page - 1) * itemPerPage).Take(itemPerPage);

            var dtos = _mapper.Map<List<LinhKienDTO>>(LKPagination);
            foreach (var dto in dtos)
            {
                var hinh = dto.Hinh.Split(',')[0];
                dto.Hinh = hinh;
            }
            //pagination
            var pagination = PaginationServices<LinhKienDTO>.PaginationLinhKien(dtos, page, itemPerPage, pageCount, searchString, searchCategory, searchManu);

            //Get All Category
            var categorys = await _llkRepository.getAll();
            var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
            ViewBag.Category = categoryDTO;

            //Get All Manufactuer
            var manufactuers = await _nccRepository.getAll();
            var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
            ViewBag.Manu = manuDTO;


            return View("~/Views/Admin/Product/Index.cshtml", pagination);
        }

        [HttpGet("Add")]
        public async Task<IActionResult> Add()
        {
            ProductAddViewModel dto = new ProductAddViewModel();

            //Get All Category
            var categorys = await _llkRepository.getAll();
            var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
            ViewBag.Category = categoryDTO;

            //Get All Manufactuer
            var manufactuers = await _nccRepository.getAll();
            var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
            ViewBag.Manu = manuDTO;

            return View("~/Views/Admin/Product/Add.cshtml", dto);
        }

        [HttpPost("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost([FromForm] ProductAddViewModel dto)
        {
            if (!ModelState.IsValid)
            {
                //Get All Category
                var categorys = await _llkRepository.getAll();
                var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
                ViewBag.Category = categoryDTO;

                //Get All Manufactuer
                var manufactuers = await _nccRepository.getAll();
                var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
                ViewBag.Manu = manuDTO;

                return View("~/Views/Admin/Product/Add.cshtml", dto);
            }

            //Lưu Hình vào Server
            string contentRootPath = _webHostEnvironment.ContentRootPath;
            string pathS = "";
            Random rnd = new Random();
            pathS = Path.Combine(contentRootPath, "images");
            pathS = Path.Combine(pathS, "products");
            string Hinh = "";
            foreach (var formFile in dto.files)
            {
                if (formFile.Length > 0)
                {
                    try
                    {
                        string fileName = dto.MaLK + rnd.Next(1, 100000) + Path.GetExtension(formFile.FileName);
                        string _path = Path.Combine(contentRootPath, "wwwroot\\images");
                        _path = Path.Combine(_path, "products");
                        _path = Path.Combine(_path, fileName);
                        using (var fileStream = new FileStream(_path, FileMode.Create))
                        {
                            await formFile.CopyToAsync(fileStream);
                        }
                        Hinh += fileName + ",";
                    }
                    catch
                    {
                        //Get All Category
                        var categorys = await _llkRepository.getAll();
                        var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
                        ViewBag.Category = categoryDTO;

                        //Get All Manufactuer
                        var manufactuers = await _nccRepository.getAll();
                        var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
                        ViewBag.Manu = manuDTO;
                        ModelState.AddModelError("Hinh", "Upload hình không thành công");
                        return View("~/Views/Admin/Product/Add.cshtml", dto);
                    }
                }
            }
            Hinh = Hinh.Remove(Hinh.Length - 1);

            //Create Entity
            LinhKien lk = new LinhKien();
            lk.TenLK = dto.TenLK;
            lk.MaLK = dto.MaLK;
            lk.MoTa = dto.MoTa;
            lk.TGBH = dto.TGBH;
            lk.SLTonKho = dto.SLTonKho;

            DonGia donGia = new DonGia();
            donGia.DonGiaBan = (decimal)dto.Gia;
            donGia.GiamGia = dto.GiamGia;
            donGia.ApDung = true;
            donGia.Ngay = DateTime.Now.Date;

            List<DonGia> donGias = new List<DonGia>();
            donGias.Add(donGia);
            lk.DonGias = donGias;

            var loaillk = await _llkRepository.getById(dto.Loai);
            var ncc = await _nccRepository.getById(dto.NCC);
            lk.Loai = loaillk;
            lk.NCC = ncc;
            lk.Hinh = Hinh;

            await _linhKienRepository.Add(lk);

            return Redirect("/admin/product");
        }

        [HttpGet("{id?}/Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var linhkien = await _linhKienRepository.getById(id);


            if (linhkien == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            LinhKienDTO dto = _mapper.Map<LinhKienDTO>(linhkien);

            //Get All Category
            var categorys = await _llkRepository.getAll();
            var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
            ViewBag.Category = categoryDTO;

            //Get All Manufactuer
            var manufactuers = await _nccRepository.getAll();
            var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
            ViewBag.Manu = manuDTO;

            var images = dto.Hinh.Split(",");
            ViewBag.Hinh = images;

            return View("~/Views/Admin/Product/Edit.cshtml", dto);
        }

        [HttpPost("{id?}/Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int id, [FromForm] List<IFormFile> files, [FromForm] LinhKienDTO dto, [FromForm] List<string> oldFiles)
        {
            if (oldFiles.Count == 0 && (files == null || files.Count == 0))
            {
                //Get All Category
                var categorys = await _llkRepository.getAll();
                var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
                ViewBag.Category = categoryDTO;

                //Get All Manufactuer
                var manufactuers = await _nccRepository.getAll();
                var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
                ViewBag.Manu = manuDTO;

                var imagesE = dto.Hinh.Split(",");
                ViewBag.Hinh = imagesE;
                ModelState.AddModelError("Hinh", "Thêm ít nhất một hình");

                return View("~/Views/Admin/Product/Edit.cshtml", dto);
            }

            if (!ModelState.IsValid)
            {
                //Get All Category
                var categorys = await _llkRepository.getAll();
                var categoryDTO = _mapper.Map<List<LoaiLinhKienDTO>>(categorys);
                ViewBag.Category = categoryDTO;

                //Get All Manufactuer
                var manufactuers = await _nccRepository.getAll();
                var manuDTO = _mapper.Map<List<NhaCungCapDTO>>(manufactuers);
                ViewBag.Manu = manuDTO;

                var imagesE = dto.Hinh.Split(",");
                ViewBag.Hinh = imagesE;

                return View("~/Views/Admin/Product/Edit.cshtml", dto);
            }

GearMVC/Controllers/Admin/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.DTO;
using Application.Mapping;
using Application.ViewModels;
using AutoMapper;
using Domain.IRepository;
using GearMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GearMVC.Controllers.Admin
{
    [Route("admin/[controller]")]
    [Authorize(Roles = "Nhân viên, Admin, Quản lý")]
    public class RoleController : Controller
    {
        private readonly IRoleRepository _roleRepository;
        private readonly IMapper _mapper;
        private readonly int ItemPerPage = 10;

        public RoleController(IRoleRepository roleRepository, IMapper mapper)
        {
            _roleRepository = roleRepository;
            _mapper = mapper;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index(string searchString = "", int page = 1)
        {
            var list = await _roleRepository.Filter(searchString);
            double count = list.Count();
            double i = (double)(count / ItemPerPage);
            var pageCount = (int)Math.Ceiling(i);

            list = list.Skip((page - 1) * ItemPerPage).Take(ItemPerPage);
            var dto = _mapper.Map<List<LoaiTKDTO>>(list);

            IndexViewModel<LoaiTKDTO> returnList = PaginationServices<LoaiTKDTO>.Pagination(dto, page, ItemPerPage, pageCount, searchString);

            return View("~/Views/Admin/Role/Index.cshtml", returnList);
        }
        [HttpGet("Add")]
        [Authorize(Roles = "Admin, Quản lý")]
        public IActionResult Add()
        {
            LoaiTKDTO dto = new LoaiTKDTO();
            return View("~/Views/Admin/Role/Add.cshtml", dto);
        }

        [HttpPost("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPost(LoaiTKDTO dto)
        {
            var message = "";

            if (!ModelState.IsValid)
            {
                return View("~/Views/Admin/Role/Add.cshtml", dto);
            }

            message = "Tạo thành công";
            ViewBag.Message = message;
            var loaiTK = dto.AddMap();
            await _roleRepository.Add(loaiTK);
            return View("~/Views/Admin/Role/Add.cshtml", dto);

        }

        [HttpGet("{id?}/Edit")]
        [Authorize(Roles = "Admin, Quản lý")]
        public async Task<IActionResult> Edit(string id)
        {
            var loaiTK = await _roleRepository.getById(id);
            if (loaiTK == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            var dto = _mapper.Map<LoaiTKDTO>(loaiTK);
            return View("~/Views/Admin/Role/Edit.cshtml", dto);
        }

        [HttpPost("{id?}/Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(string id, LoaiTKDTO dto)
        {
            var message = "";

            if (!ModelState.IsValid)
            {
                return View("~/Views/Admin/Role/Edit.cshtml", dto);
            }

            var loaiTK = await _roleRepository.getById(id);

            //Update Du Lieu
            loaiTK = dto.EditMap(loaiTK);
            await _roleRepository.Update(loaiTK);
            message = "Sửa thành công";
            ViewBag.Message = message;
            return View("~/Views/Admin/Role/Edit.cshtml", dto);
        }

        [HttpPost("{id?}/Delete")]
        [Authorize(Roles = "Admin, Quản lý")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var loaiTK = await _roleRepository.getById(id);

            if (loaiTK == null)
            {
                return View("~/Views/Error/404.cshtml");
            }

            await _roleRepository.Delete(loaiTK);
            return Redirect("/admin/role");
        }
    }
}

GearMVC/Views/Shared/Pagination.cshtml
@if(Model.PageCount > 0)
{
<div class="admin-pagination">
    <ul class="pagination pagination-centered">
        @{ 
            var Title = ViewData["nameAction"];
            var NameFunction = ViewData["nameFunction"];
        }
        
        @if (Model.CurrentPage <= 1)
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action(NameFunction.ToString(), Title.ToString() , new { searchString = Model.searchString ,page = Model.CurrentPage - 1})" aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </a>
            </li>
        }

        @for (int i = 0; i < Model.PageCount; i++)
        {
            @if (i + 1 == Model.CurrentPage)
            {
                <li class="page-item active">
                    <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a href="@Url.Action(NameFunction.ToString(), Title.ToString(), new { searchString = Model.searchString ,page = i + 1})">
                        <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                    </a>
                </li>
            }

        }
        @if (Model.CurrentPage == Model.PageCount)
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action(NameFunction.ToString(), Title.ToString(), new { searchString = Model.searchString ,page = Model.CurrentPage + 1})" aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </a>
            </li>
        }
    </ul>
</div>
}

GearMVC/Views/Shared/PaginationGia.cshtml
@if(Model.PageCount > 0)
{
<div class="admin-pagination">
    <ul class="pagination pagination-centered">
        @{
            var Title = ViewData["nameController"];
            var NameFunction = ViewData["nameFunction"];
        }

        @if (Model.CurrentPage <= 1)
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href='@Url.Action(NameFunction.ToString(), Title.ToString() , new { FromDate = Model.FromDate, ToDate = Model.ToDate, ApDung = Model.ApDung ,page = Model.CurrentPage - 1})' aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </a>
            </li>
        }

        @for (int i = 0; i < Model.PageCount; i++)
        {
            @if (i + 1 == Model.CurrentPage)
            {
                <li class="page-item active">
                    <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a href="@Url.Action(NameFunction.ToString(), Title.ToString(), new { FromDate = Model.FromDate, ToDate = Model.ToDate, ApDung = Model.ApDung ,page = i + 1})">
                        <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                    </a>
                </li>
            }

        }
        @if (Model.CurrentPage == Model.PageCount )
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href='@Url.Action(NameFunction.ToString(), Title.ToString() , new { FromDate = Model.FromDate, ToDate = Model.ToDate, ApDung = Model.ApDung ,page = Model.CurrentPage + 1})' aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </a>
            </li>
        }
    </ul>
</div>
}

GearMVC/Views/Shared/PaginationLK.cshtml
@if(Model.PageCount > 0)
{
<div class="admin-pagination">
    <ul class="pagination pagination-centered">
        @{ 
            var Title = ViewData["nameController"];
            var NameFunction = ViewData["nameFunction"];
        }
        
        @if (Model.CurrentPage <= 1)
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action(NameFunction.ToString(), Title.ToString() , new { searchString = Model.searchString , searchCategory = Model.searchCategory, searchManu = Model.searchManu,page = Model.CurrentPage - 1})" aria-label="Previous">
                    <span aria-hidden="true"
                          data-page="1">«</span><span class="sr-only">Previous</span>
                </a>
            </li>
        }

        @for (int i = 0; i < Model.PageCount; i++)
        {
            @if (i + 1 == Model.CurrentPage)
            {
                <li class="page-item active">
                    <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a href="@Url.Action(NameFunction.ToString(), Title.ToString(), new { searchString = Model.searchString , searchCategory = Model.searchCategory, searchManu = Model.searchManu,page = i + 1})">
                        <span class="page-link" data-page="@(i+1)">@(i+1)</span>
                    </a>
                </li>
            }

        }
        @if (Model.CurrentPage == Model.PageCount)
        {
            <li class="page-item">
                <span class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </span>
            </li>
        }
        else
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action(NameFunction.ToString(), Title.ToString(), new { searchString = Model.searchString , searchCategory = Model.searchCategory, searchManu = Model.searchManu,page = Model.CurrentPage + 1})" aria-label="Next">
                    <span aria-hidden="true"
                          data-page="1">»</span><span class="sr-only">Next</span>
                </a>
            </li>
        }
    </ul>
</div>
}

GearMVC/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<Domain.Entity.ApplicationUser> userManager;
@inject SignInManager<Domain.Entity.ApplicationUser> signInManager;

@{
    var user = await userManager.GetUserAsync(User);
    var displayName = user.HoTen;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/css/gear.css" type="text/css">
    <link rel="stylesheet" href="~/css/gear-admin.css" type="text/css">
    <link rel="stylesheet" href="~/css/all.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/main.css" type="text/css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/css/swiper.min.css">
    <link rel="stylesheet" href="~/css/svg-with-js.css">
    <link rel="stylesheet" href="~/css/all.min.css">
    <link rel="stylesheet" href="~/css/brands.min.css">
    <link rel="stylesheet" href="~/css/regular.min.css">
    <link rel="stylesheet" href="~/css/svg-with-js.css">
    <link rel="stylesheet" href="~/css/solid.min.css">
    <link rel="stylesheet" href="~/css/v4-shims.min.css">
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="gear-admin">
        <div class="admin-right">
            <div class="admin-user">
                <div class="admin-user-text">
                    <span class="admin-user-name">@displayName</span> <img src="~/images/admin.png" height="40px">
                </div>
            </div>
            @RenderBody()
            @RenderSection("Content", false)
        </div>
        <div class="admin-left col-3">
            <div class="admin-logo-box" style="text-align: center;">
                <a href="/" style="line-height: 70px; color:white; text-align: center; font-size: 30px">GEAR SHOP</a>
            </div>
            <div class="admin-left-menu">
                <a class="dashboard" href="@Url.Action("Index","Dashboard")">
                    <div class="menu-section row">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fa fa-dashboard"></i></div><span
                                    class="menu-text">Tổng quan</span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a>
                <a class="taikhoan" href="/admin/user">
                    <div class="menu-section row" id="admin-user">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fas fa-user"></i></div><span class="menu-text">
                                    Người
                                    dùng
                                </span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a>
                <a class="loaitaikhoan" href="@Url.Action("Index","Role")">
                    <div class="menu-section row" id="admin-user">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fas fa-user-tag"></i></div><span
                                    class="menu-text">
                                    Loại tài khoản
                                </span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a><a class="sanpham" href="@Url.Action("Index","Product")">
                    <div class="menu-section row">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fab fa-product-hunt font-size-20"></i></div>
                                <span class="menu-text">Sản phẩm</span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a><a class="chungloai" href="@Url.Action("Index","Category")">
                    <div class="menu-section row">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fas fa-box font-size-20"></i></div><span
                                    class="menu-text">Chủng loại</span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a><a class="nhacungcap" href="@Url.Action("Index","Manufactuer")">
                    <div class="menu-section row">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fas fa-industry font-size-20"></i></div><span
                                    class="menu-text">Nhà sản xuất</span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a><a class="hoadon" href="@Url.Action("Index","DonHang")">
                    <div class="menu-section row">
                        <div class="col-9">
                            <div class="row">
                                <div class="col-3 text-center"><i class="fas fa-clipboard-list font-size-20"></i></div>
                                <span class="menu-text">Đơn hàng</span>
                            </div>
                        </div>
                        <div class="col-2"><span class="padding-right-5"><i
                                    class="fas fa-arrow-circle-right"></i></span></div>
                    </div>
                </a>
            </div>
        </div>
    </div>

</body>

@RenderSection("Scripts", false)